---
language: node_js
node_js:
  - "9"

sudo: false

cache:
  directories:
    - $HOME/.npm


matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install npm@5.6.0

install:
  - npm install